apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: game-2048
  name: deployment-spring
spec:
  selector:
    matchLabels:
      name: spring
  replicas: 5
  template:
    metadata:
      labels:
        name: spring
    spec:
      containers:
      - image: public.ecr.aws/m5j9q0g7/verizon:latest
        imagePullPolicy: Always
        name: spring-pod
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: game-2048
  name: service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    name: spring
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: game-2048
  namespace: game-2048
spec:
  ingressClassName: alb
  rules:
  - host: k8s-game2048-ingress2-e1d9d1f206-86903639.ap-northeast-3.elb.amazonaws.com
    http:
      paths:
      - pathType: Prefix
        path: /java-web-app
        backend:
          service:
            name: service-2048
            port:
              number: 80
